POST http://0000:9000/customer
Content-Type: application/json

{
  "id": "100",
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@company.com"
}


###
POST http://0000:9000/customer
Content-Type: application/json

{
  "id": "200",
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@company.com"
}

###
POST http://0000:9000/customer
Content-Type: application/json

{
  "id": "300",
  "firstName": "Mary",
  "lastName": "Smith",
  "email": "mary.smith@company.com"
}


###
GET http://0000:9000/customer
Accept: application/json

###
GET http://0000:9000/customer/200

###
GET http://0000:9000/customer/500

###
DELETE http://0000:9000/customer/100

###
DELETE http://0000:9000/customer/500
